title: Homebrew ドキュメント (日本語版)


remote_theme: Homebrew/brew.sh

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      search_name: Documentation
      search_site: docs